FROM node:16-alpine AS builder

WORKDIR /project

COPY package.json package-lock.json /project/

RUN npm install

COPY . /project/

RUN npm run build

FROM nginx:1.24.0-alpine

COPY --from=builder /project/build /usr/share/nginx/html

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]